AS = nasm
ASFLAGS = -O1 -f elf -g -F dwarf
LD = ld
LDFLAGS = -melf_i386

ASRCDIR = output
ASRC = $(wildcard $(ASRCDIR)/*.s)
OBJ = $(ASRC:%.s=%.o)
TARGET = main

.PHONY : all
all : $(TARGET)

$(ASRCDIR)/%.o : $(ASRCDIR)/%.s
	$(AS) $(ASFLAGS) -o $@ $<

$(TARGET) : $(OBJ)
	ld $(LDFLAGS) -o $@ $^
